### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by khanh-nguyen** [admc/wd#377]
I was simply trying the following:
```
var wd = require('wd');
var browser = wd.promiseChainRemote();
browser.init({browserName: 'chrome'})
    .get('https://www.google.com')
    .fin(function() { return browser.quit(); })
    .done();
```
but got error:
```
./node_modules/wd/node_modules/q/q.js:126
                    throw e;
                          ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:742:11)
    at Object.afterConnect [as oncomplete] (net.js:982:19)
```

If I try with wd shell, the result is as following:
```
$ node_modules/.bin/wd shell
(wd): x = wd.remote()
(wd): x.init({browserName: 'chrome'})
undefined
(wd): x.get('https://www.google.com')
undefined
(wd): x.eval("window.location.href", function(e, o) { console.log(o) })
undefined
(wd): x.quit()
undefined
```
This was run on Maverick, node@0.11.14. Chrome driver has been installed.

**Comment by sebv** [comment]
What are you trying to connect to?

**Comment by khanh-nguyen** [comment]
Ah, thanks for your response @sebv. I should've run selenium locally. 
It's clear now.
