### ISSUE TITLE
Chrome driver does not launch‏

### ISSUE THREAD

**Issue by yanhualovegirl** [admc/wd#381]
I had installed you awesome selenium-standalone server. When I run `selenium-standalone start` and an example script from https://github.com/admc/wd, 

mocha ./examples/promise/mocha-specs.js

The chromedriver does not startup, could you please tell me what is the problem.

Message from terminal:

23:47:52.597 INFO - Executing: [new session: Capabilities [{browserName=chrome, javascriptEnabled=true, version=, platform=ANY}]])

23:47:52.609 INFO - Creating a new session for Capabilities [{browserName=chrome, javascriptEnabled=true, version=, platform=ANY}]

Starting ChromeDriver 2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf) on port 7240

Only local connections are allowed.

23:48:02.627 INFO - Executing: [new session: Capabilities [{browserName=chrome, javascriptEnabled=true, version=, platform=ANY}]])

23:48:02.629 INFO - Creating a new session for Capabilities [{browserName=chrome, javascriptEnabled=true, version=, platform=ANY}]

Starting ChromeDriver 2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf) on port 31279

Only local connections are allowed.

23:48:12.901 WARN - Exception thrown

java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException

Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'

System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.1', java.version: '1.8.0_31'

Driver info: driver.version: unknown

at java.util.concurrent.FutureTask.report(FutureTask.java:122)

at java.util.concurrent.FutureTask.get(FutureTask.java:192)

at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:175)

at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:111)

at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:88)

at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:109)

at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:57)

at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)

at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:110)

at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:172)

at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:201)

at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:163)

at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:129)

at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)

at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)

at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)

at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)

at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)

at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)

at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)

at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)

at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)

at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)

at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)

at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)

Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException

Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'

System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.1', java.version: '1.8.0_31'

Driver info: driver.version: unknown

at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:69)

at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:53)

at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:54)

at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:214)

at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.reflect.InvocationTargetException

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:408)

at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)

... 9 more

**Comment by vvo** [comment]
I really think this is a selenium issue, selenium-standalone is only a wrapper. maybe try to run selenium itself http://www.seleniumhq.org/
