### ISSUE TITLE
Cannot connect to Selenium Grid 2.52

### ISSUE THREAD

**Issue by ethannguyens** [admc/wd#424]
Hi,

I cannot connect to the selenium grid version 2.52 with the below error from the selenium grid hub:

`15:12:31.379 INFO - Got a request to create a new session: Capabilities [{appium-version=1.4.13, platformVersion=5.1, browserName=chrome, platformName=ANDROID, deviceName=********}]
2016-02-18 15:12:31.433:WARN:osjs.ServletHandler:qtp1484594489-18: /wd/hub/session
java.io.IOException: java.lang.IllegalStateException: Not a JSON Object: null
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:126)
	at org.openqa.grid.web.servlet.DriverServlet.doDelete(DriverServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at org.openqa.grid.web.servlet.handler.WebDriverRequest.extractDesiredCapability(WebDriverRequest.java:69)
	at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.<init>(SeleniumBasedRequest.java:103)
	at org.openqa.grid.web.servlet.handler.WebDriverRequest.<init>(WebDriverRequest.java:40)
	at org.openqa.grid.web.servlet.handler.WebDriverRequestFactory.createFromRequest(WebDriverRequestFactory.java:30)
	at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.createFromRequest(SeleniumBasedRequest.java:74)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:81)
	at org.openqa.grid.web.servlet.DriverServlet.doDelete(DriverServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)`

The test code using wdjs
`
require("./helpers/setup");`

var wd = require("wd"),
    _ = require('underscore'),
    serverConfigs = require('./helpers/appium-servers');

describe("android bundle", function () {
    this.timeout(300000);
    var driver;
    var allPassed = true;

    before(function () {
        var serverConfig = process.env.SAUCE ?
            serverConfigs.sauce : serverConfigs.local;
        driver = wd.promiseChainRemote(serverConfig);
        require("./helpers/logging").configure(driver);

        var desired = process.env.SAUCE ?
            _.clone(require("./helpers/caps").android18) :
            _.clone(require("./helpers/caps").android19);
        desired.browserName = 'chrome';
        if (process.env.SAUCE) {
            desired.name = 'android - browser';
            desired.tags = ['sample'];
        }
        return driver.init(desired);

    });
`

And the server config:

`exports.local = {
  host: 'localhost',
  port: 4444
};`

I can connect and run the test using Python Client.
Is that the `wd.promiseChainRemote(serverConfig);` doesn't send the JSON request correctly to the Selenium Grid?

Any suggestions will be greatly appreciated.

**Comment by ethannguyens** [comment]
@admc @javruben @peterbraden @sebv @Pita @jlipps @pdsarin @OniOni @btipling @santiycr @bernii @maudineormsby @MattiSG

Ay suggestions? Cuz i really enjoy wd js than webdriver io

**Comment by sebv** [comment]
I don't see anything wrong with your client code, but we won't be able to debug the selenium grid without being on it.
