### ISSUE TITLE
Global installation fails with EACCESS error

### ISSUE THREAD

**Issue by guss77** [admc/wd#483]
When trying to install wd globally, installation fails with an error:

```
# node --version
v8.2.1
# npm --version
5.3.0
# npm install -g wd
...
npm info lifecycle wd@1.4.0~install: wd@1.4.0

> wd@1.4.0 install /usr/local/lib/node_modules/wd
> node scripts/build-browser-scripts

/usr/local/lib/node_modules/wd/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/wd/build'
    at Object.fs.mkdirSync (fs.js:891:18)
    at sync (/usr/local/lib/node_modules/wd/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/wd/scripts/build-browser-scripts.js:6:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
npm info lifecycle wd@1.4.0~install: Failed to exec install script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wd@1.4.0 install: `node scripts/build-browser-scripts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wd@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-04T10_38_27_165Z-debug.log
```

The log file reported above ends with these lines:

```
2775 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "wd"
2776 verbose node v8.2.1
2777 verbose npm  v5.3.0
2778 error code ELIFECYCLE
2779 error errno 1
2780 error wd@1.4.0 install: `node scripts/build-browser-scripts`
2780 error Exit status 1
2781 error Failed at the wd@1.4.0 install script.
2781 error This is probably not a problem with npm. There is likely additional logging output above.
2782 verbose exit [ 1, true ]
```

This works fine in NodeJS 6

This problem is the cause of a polymer-cli installation issue: https://github.com/Polymer/polymer-cli/issues/832 , https://github.com/Polymer/polymer-cli/issues/836#issuecomment-320201006 (and probably other reports).

It may be interesting to note that while, as expected, the directory `/usr/local/lib/node_modules/wd/build` doesn't exist after this error, neither is the directory `/usr/local/lib/node_modules/wd`.

**Comment by guss77** [comment]
The problem appears to be with the latest version of NPM, not with NodeJS - updating NPM to version 5.3.0 on NodeJS 6 causes the same problem to occur.

**Comment by guss77** [comment]
I still can't figure out why NPM v5.3.0 changed the file permissions of global modules to `root`, but as it still runs scripts using the `nobody` user (as an be seen by running `npm -g config get user`) then the `EACCESS` error is obvious - the script tries to create the `build` directory in a `root` owner directory as the `nobody` user.

**Comment by guss77** [comment]
As details in the NPM issue linked above, the problem is a regression in NPM and can be also worked around by setting `--unsafe-perm`

**Comment by MrCsabaToth** [comment]
`--unsafe-perm` helped, but this has to be fixed.

https://pbs.twimg.com/media/CHKb0FSUwAIZqy5.jpg

**Comment by rechlin** [comment]
I ran into this on Linux. Still a problem. Seems to be something that can be corrected in wd, as other packages can create folders.

**Comment by dcb99** [comment]
Running into this same problem on OS-X High Sierra. Total pain, but --unsafe-perm allowed the install to work.

**Comment by dman777** [comment]
same here... linux.

**Comment by dresh** [comment]
any clue when this issue will be fixed?

**Comment by DarkSideOfMo0n** [comment]
Any Updates? This still is a major Problem and fucks up lots of other repos that try using this. for instance web-component-test

**Comment by admc** [comment]
Everything I'm reading says that this is an NPM permissions symlink situation: https://docs.npmjs.com/getting-started/fixing-npm-permissions - does anyone actually know how I can fix this in the package? If so I would be happy to fix and do a release.

**Comment by admc** [comment]
@jlipps any ideas?

**Comment by jlipps** [comment]
It does sound like an NPM issue. Could we work around it by making sure that all files are written to /tmp? What files need writing anyway during install?
