### ISSUE TITLE
Use local version of gemini

### ISSUE THREAD

**Issue by nquinn721** [admc/wd#484]
Was just wondering if it's possible to use the local package version of gemini in ./node_modules/.bin/gemini. When I try to use it it throws this error:

Error: Cannot find module './build/Release/png_img'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/r568786/projects/digital-ui-area/node_modules/png-img/index.js:4:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/r568786/projects/digital-ui-area/node_modules/gemini/lib/image/index.js:5:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/r568786/projects/digital-ui-area/node_modules/gemini/lib/browser/camera.js:3:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

**Comment by j0tunn** [comment]
@nquinn721 Thats not the wd issue. Move it to gemini repo, and please add more details: like `npm i` log, `gemini`, `npm` and `node` versions
