### ISSUE TITLE
Unexpected data in simpleCallback

### ISSUE THREAD

**Issue by funkyvisions** [admc/wd#514]
I'm getting an error down in the bowels of wd.  This only happens maybe 1 out of 30 tests that I run.
```
Error: [context()] Unexpected data in simpleCallback.
         at exports.newError (/Users/daviesd/workspace/wms-circ-app/node_modules/wd/lib/utils.js:145:13)
         at /Users/daviesd/workspace/wms-circ-app/node_modules/wd/lib/callbacks.js:42:12
         at /Users/daviesd/workspace/wms-circ-app/node_modules/wd/lib/webdriver.js:179:5
         at Request._callback (/Users/daviesd/workspace/wms-circ-app/node_modules/wd/lib/http-utils.js:88:7)
         at Request.self.callback (/Users/daviesd/workspace/wms-circ-app/node_modules/wd/node_modules/request/request.js:186:22)
         at emitTwo (events.js:125:13)
         at Request.emit (events.js:213:7)
         at Request.<anonymous> (/Users/daviesd/workspace/wms-circ-app/node_modules/wd/node_modules/request/request.js:1081:10)
         at emitOne (events.js:115:13)
         at Request.emit (events.js:210:7)
         at IncomingMessage.<anonymous> (/Users/daviesd/workspace/wms-circ-app/node_modules/wd/node_modules/request/request.js:1001:12)
         at Object.onceWrapper (events.js:314:30)
         at emitNone (events.js:110:20)
         at IncomingMessage.emit (events.js:207:7)
         at endReadableNT (_stream_readable.js:1059:12)
         at _combinedTickCallback (internal/process/next_tick.js:138:11)
```
This seems similar to what was discuss in https://github.com/admc/wd/issues/478.

I put some logging in callback.js and "data" is equal to this
`Parameters were incorrect. We wanted {"required":["name"]} and you sent []`

Not sure where to keep digging.  Can you provide any guidance?  It fails just as the test is starting up and it's not necessarily the same test that fails each time.  It's random and infrequent, but still an annoyance.

**Comment by senaev** [comment]
i have the same exact problem
